### ISSUE TITLE
判断事件分发的条件似乎有小疏漏

### ISSUE THREAD

**Issue by heruoxin** [drakeet/GenerousRecyclerView#1]
几天前在群里看到了乃的文章，正好碰到一样的问题，于是感谢！
不过这一句判断窝觉得好像有点问题：
`mScrollY < getPaddingTop() && ev.getY() < getPaddingTop()`
当仅滚动了 y < paddingTop 的一小段距离后，在屏幕座标 y 属于 [paddingTop-y, paddingTop] 的这一小段区域中的触摸事件会被误分发下去。
个人觉得似乎应该改成 `ev.getY() + mScrollY < getPaddingTop()` 。

**Comment by drakeet** [comment]
感谢反馈，我明天测试下！

little_cup <notifications@github.com>于2015年11月1日周日 22:55写道：

**Comment by drakeet** [comment]
已经采纳，感谢！
